DROP DATABASE IF EXISTS livros;
CREATE DATABASE livros;

USE livros;

CREATE TABLE USERS(
    USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(50) NOT NULL,
    USR_EMAIL VARCHAR(30),
    USR_PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(USR_ID)
    
);

/*
CREATE TABLE MSG(
	
    MSG_ID INT NOT NULL AUTO_INCREMENT,
    MSG_USER TEXT(1000) NOT NULL,
    PRIMARY KEY(MSG_ID)
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
    
);

*/

CREATE TABLE LIVROS( 
    LV_ID INT NOT NULL AUTO_INCREMENT,
    LV_NOME VARCHAR(250) NOT NULL,
    LV_GENERO VARCHAR(250) NOT NULL,
    LV_ESCRITOR VARCHAR(250) NOT NULL,
    LV_ANO VARCHAR(250) NOT NULL,
    USR_ID INT NOT NULL,
    PRIMARY KEY(LV_ID),
    /*FOREIGN KEY(USR_ID) REFERENCES USERS (USR_ID)*/
CONSTRAINT FK_USER FOREIGN KEY (USR_ID) REFERENCES USERS (USR_ID)
);
